# Exclude stuff
exclude: [Gemfile, Gemfile.lock, README.md]

# Site settings
title: Serendipity Blog System
description: Serendipity is a PHP-powered weblog engine giving users an easy way to maintain a blog and developers a framework with the power for professional applications.
baseurl: ""

# Build settings
markdown: kramdown

# kramdown options
kramdown:
    auto_id_prefix: 'docs-'

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
